### ISSUE TITLE
API docs: -moz- & -o- not needed

### ISSUE THREAD

**Issue by tomByrer** [dinbror/blazy#4]
http://dinbror.dk/blog/blazy/#Multi

``` css
    .b-lazy {
        -webkit-transition: opacity 500ms ease-in-out 100ms;  /* Android =<4.3, iOS =< 6.1 */
/*         -moz-transition: opacity 500ms ease-in-out 100ms;
             -o-transition: opacity 500ms ease-in-out 100ms;
no longer needed http://caniuse.com/css-transitions */
                transition: opacity 500ms ease-in-out 100ms;
}
```

Thanks :)
